use_frameworks!
platform :ios, '11.0'

target 'SuperResolutionKit_Example' do
  pod 'SuperResolutionKit', :path => '../'

  target 'SuperResolutionKit_Tests' do
    inherit! :search_paths

    
  end
end
